load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["params.go"],
    importpath = "github.com/joesonw/drlee/pkg/core/helpers/params",
    visibility = ["//visibility:public"],
    deps = ["@com_github_yuin_gopher_lua//:go_default_library"],
)
