name: Go

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - uses: actions/checkout@v2

      - name: Setup build tools
        run: |
          sudo apt-get install git
          go get github.com/bazelbuild/bazelisk
          go get github.com/gobuffalo/packr/packr

      - name: Setup requirements
        run: |
          bazelisk build //_proto:go_default_library
          go mod download
          packr

      - name: lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27

      - name: Test
        run: go test -v ./...

      - name: Build
        env:
          BAZEL_BIN: bazelisk
        run: |
          ./hack/build_binaries.sh
          ls -al binaries

      - name: Publish
        env:
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        run: |
          curl -T binaries/drlee-darwin-amd64 -ujoesonw:${BINTRAY_API_KEY} -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/joesonw/drlee/drlee/latest/drlee-darwin-amd64
          curl -T binaries/drlee-linux-amd64 -ujoesonw:${BINTRAY_API_KEY} -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/joesonw/drlee/drlee/latest/drlee-linux-amd64
          curl -T binaries/drlee-windows-amd64.exe -ujoesonw:${BINTRAY_API_KEY} -H "X-Bintray-Publish: 1" -H "X-Bintray-Override: 1" https://api.bintray.com/content/joesonw/drlee/drlee/latest/drlee-windows-amd64.exe


